version: 2

jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: docker:18.03-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            docker build -t quay.io/gunosy/neologd-for-igo .
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              export TAG=`date +%Y.%m.%d`
              docker login -u "$QUAY_IO_USERNAME -p "$QUAY_IO_PASSWORD"
              docker tag quay.io/gunosy/neologd-for-igo quay.io/gunosy/neologd-for-igo:"$TAG"
              docker push quay.io/gunosy/neologd-for-igo:"$TAG"
              docker tag quay.io/gunosy/neologd-for-igo quay.io/gunosy/neologd-for-igo:latest
              docker push quay.io/gunosy/neologd-for-igo:latest
            fi

workflows:
  version: 2
  workflow:
    triggers:
      - schedule:
          cron: "0 0 * * 2,5"
          filters:
            branches:
              only:
                - master
    jobs:
      - build

